import type { Metadata } from 'next';
import Link from 'next/link';
import type { Invoice, PaginationMeta } from '@manas/shared';
import { apiFetchSafe } from '@/lib/api';
import { Card, PageHeader } from '@/components/ui/Card';
import { DataTable } from '@/components/ui/DataTable';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { DateFilter, FilterBar, FilterSelect, Pagination, SearchInput } from '@/components/ui/Filters';
import { formatDate, formatMoney } from '@/lib/format';

export const metadata: Metadata = { title: 'Invoices' };

type InvoiceRow = Invoice & { student_name: string; student_code: string };

export default async function InvoicesPage({
  searchParams,
}: {
  searchParams: Record<string, string | undefined>;
}) {
  const page = Number.parseInt(searchParams.page ?? '1', 10);

  const result = await apiFetchSafe<InvoiceRow[]>(
    '/invoices',
    {
      query: {
        page,
        pageSize: 20,
        branchId: searchParams.branchId,
        status: searchParams.status,
        from: searchParams.from,
        to: searchParams.to,
        search: searchParams.search,
      },
    },
    [],
  );

  const meta: PaginationMeta = result.meta ?? { page, pageSize: 20, total: 0, totalPages: 0 };

  return (
    <>
      <PageHeader
        title="Invoices"
        description="Invoices are generated by the admission workflow. Totals are calculated server-side."
      />

      <FilterBar>
        <SearchInput placeholder="Invoice number or student…" />
        <FilterSelect
          paramName="status"
          label="Status"
          options={[
            { value: 'PENDING', label: 'Pending' },
            { value: 'PARTIALLY_PAID', label: 'Partially paid' },
            { value: 'PAID', label: 'Paid' },
            { value: 'OVERDUE', label: 'Overdue' },
            { value: 'CANCELLED', label: 'Cancelled' },
          ]}
        />
        <DateFilter paramName="from" label="From" />
        <DateFilter paramName="to" label="To" />
      </FilterBar>

      <Card padded={false}>
        <DataTable
          rows={result.data}
          rowKey={(row) => row.id}
          error={result.error}
          caption="Invoices"
          emptyTitle="No invoices"
          emptyDescription="Invoices appear here once admissions are processed."
          columns={[
            {
              key: 'number',
              header: 'Invoice',
              render: (row) => (
                <div>
                  <Link
                    href={`/invoices/${row.id}`}
                    className="font-medium tabular-nums text-brand hover:underline"
                  >
                    {row.invoice_number}
                  </Link>
                  <p className="text-xs text-content-subtle">
                    {formatDate(row.invoice_date)}
                  </p>
                </div>
              ),
            },
            {
              key: 'student',
              header: 'Student',
              render: (row) => (
                <Link
                  href={`/students/${row.student_id}`}
                  className="text-content hover:underline"
                >
                  {row.student_name}
                </Link>
              ),
            },
            {
              key: 'due',
              header: 'Due',
              secondary: true,
              render: (row) => (
                <span className="tabular-nums text-content-muted">
                  {formatDate(row.due_date)}
                </span>
              ),
            },
            {
              key: 'total',
              header: 'Total',
              align: 'right',
              render: (row) => <span className="tabular-nums">{formatMoney(row.total)}</span>,
            },
            {
              key: 'paid',
              header: 'Paid',
              align: 'right',
              secondary: true,
              render: (row) => (
                <span className="tabular-nums text-positive">
                  {formatMoney(row.amount_paid)}
                </span>
              ),
            },
            {
              key: 'balance',
              header: 'Balance',
              align: 'right',
              render: (row) => (
                <span
                  className={
                    Number(row.balance) > 0
                      ? 'tabular-nums font-medium text-warning'
                      : 'tabular-nums'
                  }
                >
                  {formatMoney(row.balance)}
                </span>
              ),
            },
            {
              key: 'status',
              header: 'Status',
              align: 'right',
              render: (row) => <StatusBadge status={row.status} />,
            },
          ]}
        />
        <Pagination {...meta} />
      </Card>
    </>
  );
}
