-- Manas Library — complete schema, ordered for a single manual run.
--
-- Generated from database/migrations/*.sql. Do NOT edit this file; edit the
-- numbered migrations and regenerate, or later runs of the migration runner
-- will report a checksum mismatch.
--
-- HOW TO RUN
--   Supabase Dashboard -> SQL Editor -> New query -> paste all of this -> Run.
--   It is wrapped in a single transaction: if any statement fails, nothing is
--   applied and you can fix and re-run from a clean slate.
--
-- The final INSERT records these migrations as applied so a later
-- `npm run migrate` skips them instead of trying to re-create everything.

BEGIN;


-- ========================================================================
-- 0001_extensions_and_enums.sql
-- ========================================================================

-- 0001 — Extensions, enum types and shared helpers.
-- Everything in this project lives in the `public` schema; Supabase owns `auth`.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";   -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "btree_gist"; -- exclusion constraints on (uuid, daterange)
CREATE EXTENSION IF NOT EXISTS "citext";     -- case-insensitive email/codes

-- --------------------------------------------------------------------------
-- Enum types (mirrored in packages/shared/src/enums.ts)
-- --------------------------------------------------------------------------
CREATE TYPE user_role            AS ENUM ('SUPER_ADMIN', 'BRANCH_ADMIN', 'STAFF');
CREATE TYPE user_status          AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED');
CREATE TYPE branch_status        AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED');
CREATE TYPE student_status       AS ENUM ('ACTIVE', 'INACTIVE', 'EXPIRED', 'SUSPENDED');
CREATE TYPE plan_status          AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE seat_status          AS ENUM ('AVAILABLE', 'OCCUPIED', 'RESERVED', 'MAINTENANCE', 'INACTIVE');
CREATE TYPE seat_type            AS ENUM ('STANDARD', 'CABIN', 'AC', 'NON_AC');
CREATE TYPE allocation_status    AS ENUM ('ACTIVE', 'RELEASED', 'TRANSFERRED', 'EXPIRED', 'CANCELLED');
CREATE TYPE batch_status         AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE enrollment_status    AS ENUM ('ACTIVE', 'COMPLETED', 'TRANSFERRED', 'CANCELLED');
CREATE TYPE admission_status     AS ENUM ('PENDING', 'CONFIRMED', 'EXPIRED', 'CANCELLED');
CREATE TYPE invoice_status       AS ENUM ('DRAFT', 'PENDING', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED');
CREATE TYPE payment_method       AS ENUM ('CASH', 'UPI', 'BANK_TRANSFER', 'CARD', 'OTHER');
CREATE TYPE payment_status       AS ENUM ('COMPLETED', 'REVERSED');
CREATE TYPE fee_schedule_status  AS ENUM ('UPCOMING', 'DUE', 'PAID', 'OVERDUE', 'CANCELLED');
CREATE TYPE reminder_type        AS ENUM ('UPCOMING', 'DUE_TODAY', 'OVERDUE');
CREATE TYPE reminder_status      AS ENUM ('PENDING', 'SENT', 'FAILED', 'SKIPPED');
CREATE TYPE attendance_source    AS ENUM ('MANUAL', 'BIOMETRIC', 'IMPORTED');
CREATE TYPE attendance_status    AS ENUM ('PRESENT', 'ABSENT', 'LATE');
CREATE TYPE device_status        AS ENUM ('ACTIVE', 'INACTIVE', 'ERROR');

-- --------------------------------------------------------------------------
-- Shared trigger: keep updated_at honest regardless of what the client sends.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.set_updated_at() IS
  'Attach as BEFORE UPDATE trigger on every table carrying updated_at.';


-- ========================================================================
-- 0002_core_identity.sql
-- ========================================================================

-- 0002 — Branches, roles, application users and branch assignments.
--
-- Identity is owned by Supabase Auth (auth.users). public.users is the
-- application profile: role, status and branch assignments. The Node API is
-- the only writer.

CREATE TABLE public.branches (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_code   citext NOT NULL UNIQUE,
  name          text NOT NULL,
  address       text,
  city          text,
  state         text,
  phone         text,
  email         citext,
  opening_time  time,
  closing_time  time,
  status        branch_status NOT NULL DEFAULT 'ACTIVE',
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT branches_code_format CHECK (branch_code ~ '^[A-Za-z0-9_-]{2,20}$'),
  CONSTRAINT branches_name_not_blank CHECK (length(btrim(name)) > 0)
);

CREATE INDEX idx_branches_status ON public.branches (status);

CREATE TRIGGER trg_branches_updated_at
  BEFORE UPDATE ON public.branches
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Role lookup table (PRD §33). The enum drives type safety; this table exists
-- so roles are describable/queryable and can carry future metadata.
CREATE TABLE public.roles (
  code        user_role PRIMARY KEY,
  name        text NOT NULL,
  description text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.roles (code, name, description) VALUES
  ('SUPER_ADMIN',  'Super Admin',  'Franchise-wide access across every branch.'),
  ('BRANCH_ADMIN', 'Branch Admin', 'Full management of assigned branches only.'),
  ('STAFF',        'Staff',        'Day-to-day operations within assigned branches.');

CREATE TABLE public.users (
  id            uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  email         citext NOT NULL UNIQUE,
  full_name     text NOT NULL,
  phone         text,
  role          user_role NOT NULL REFERENCES public.roles (code),
  status        user_status NOT NULL DEFAULT 'ACTIVE',
  created_by    uuid REFERENCES public.users (id) ON DELETE SET NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT users_full_name_not_blank CHECK (length(btrim(full_name)) > 0)
);

CREATE INDEX idx_users_role   ON public.users (role);
CREATE INDEX idx_users_status ON public.users (status);

CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Branch authorisation. A SUPER_ADMIN needs no rows here (implicitly all
-- branches); every other role is limited to the branches listed.
CREATE TABLE public.user_branches (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  branch_id   uuid NOT NULL REFERENCES public.branches (id) ON DELETE CASCADE,
  is_primary  boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, branch_id)
);

CREATE INDEX idx_user_branches_user   ON public.user_branches (user_id);
CREATE INDEX idx_user_branches_branch ON public.user_branches (branch_id);

-- At most one primary branch per user.
CREATE UNIQUE INDEX uq_user_branches_primary
  ON public.user_branches (user_id)
  WHERE is_primary;

-- --------------------------------------------------------------------------
-- Authorisation helpers. Used by RLS policies (migration 0010) so the browser
-- session can read its own branches directly for Realtime subscriptions.
-- SECURITY DEFINER + a locked-down search_path so policies cannot recurse.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.current_role_code()
RETURNS user_role
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT u.role
  FROM public.users u
  WHERE u.id = auth.uid() AND u.status = 'ACTIVE';
$$;

CREATE OR REPLACE FUNCTION public.is_super_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT coalesce(public.current_role_code() = 'SUPER_ADMIN', false);
$$;

CREATE OR REPLACE FUNCTION public.has_branch_access(target_branch_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT public.is_super_admin()
     OR EXISTS (
       SELECT 1
       FROM public.user_branches ub
       JOIN public.users u ON u.id = ub.user_id
       WHERE ub.user_id = auth.uid()
         AND ub.branch_id = target_branch_id
         AND u.status = 'ACTIVE'
     );
$$;


-- ========================================================================
-- 0003_students_memberships.sql
-- ========================================================================

-- 0003 — Students and membership plans.

CREATE TABLE public.membership_plans (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name           text NOT NULL UNIQUE,
  duration_days  integer NOT NULL,
  price          numeric(12, 2) NOT NULL,
  description    text,
  status         plan_status NOT NULL DEFAULT 'ACTIVE',
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT membership_plans_duration_positive CHECK (duration_days > 0),
  CONSTRAINT membership_plans_price_non_negative CHECK (price >= 0)
);

CREATE INDEX idx_membership_plans_status ON public.membership_plans (status);

CREATE TRIGGER trg_membership_plans_updated_at
  BEFORE UPDATE ON public.membership_plans
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.students (
  id                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_code             citext NOT NULL UNIQUE,
  branch_id                uuid NOT NULL REFERENCES public.branches (id) ON DELETE RESTRICT,
  full_name                text NOT NULL,
  mobile                   text NOT NULL,
  email                    citext,
  date_of_birth            date,
  address                  text,
  emergency_contact_name   text,
  emergency_contact_phone  text,
  photo_url                text,
  status                   student_status NOT NULL DEFAULT 'ACTIVE',
  created_by               uuid REFERENCES public.users (id) ON DELETE SET NULL,
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT students_full_name_not_blank CHECK (length(btrim(full_name)) > 0),
  CONSTRAINT students_mobile_format CHECK (mobile ~ '^[0-9]{10,15}$'),
  CONSTRAINT students_dob_past CHECK (date_of_birth IS NULL OR date_of_birth < CURRENT_DATE)
);

-- Redundant on its own, but lets child tables declare a composite foreign key
-- (student_id, branch_id) so the database itself rejects a row that mixes a
-- student from one branch with another branch's context. Branch isolation is
-- enforced structurally, not only in application code.
ALTER TABLE public.students
  ADD CONSTRAINT uq_students_id_branch UNIQUE (id, branch_id);

-- A mobile number identifies one student inside a branch. The same person may
-- legitimately exist at two branches, so the constraint is branch-scoped.
CREATE UNIQUE INDEX uq_students_branch_mobile
  ON public.students (branch_id, mobile);

CREATE INDEX idx_students_branch  ON public.students (branch_id);
CREATE INDEX idx_students_status  ON public.students (status);
CREATE INDEX idx_students_mobile  ON public.students (mobile);
CREATE INDEX idx_students_branch_status ON public.students (branch_id, status);

-- Trigram-free prefix search on name, adequate for admin-console volumes.
CREATE INDEX idx_students_name_lower ON public.students (lower(full_name) text_pattern_ops);

CREATE TRIGGER trg_students_updated_at
  BEFORE UPDATE ON public.students
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ========================================================================
-- 0004_seats_allocations.sql
-- ========================================================================

-- 0004 — Seats and seat allocations.
--
-- The overlap rule (PRD §11.2) is enforced by an EXCLUDE constraint rather
-- than application logic, so a race between two concurrent allocations can
-- never produce a double-booked seat.

CREATE TABLE public.seats (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id    uuid NOT NULL REFERENCES public.branches (id) ON DELETE RESTRICT,
  seat_number  citext NOT NULL,
  floor        text,
  section      text,
  seat_type    seat_type NOT NULL DEFAULT 'STANDARD',
  status       seat_status NOT NULL DEFAULT 'AVAILABLE',
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT seats_number_not_blank CHECK (length(btrim(seat_number::text)) > 0),
  CONSTRAINT uq_seats_branch_number UNIQUE (branch_id, seat_number),
  CONSTRAINT uq_seats_id_branch UNIQUE (id, branch_id)
);

CREATE INDEX idx_seats_branch        ON public.seats (branch_id);
CREATE INDEX idx_seats_status        ON public.seats (status);
CREATE INDEX idx_seats_branch_status ON public.seats (branch_id, status);

CREATE TRIGGER trg_seats_updated_at
  BEFORE UPDATE ON public.seats
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.seat_allocations (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id     uuid NOT NULL REFERENCES public.branches (id) ON DELETE RESTRICT,
  seat_id       uuid NOT NULL,
  student_id    uuid NOT NULL,
  start_date    date NOT NULL,
  end_date      date,
  status        allocation_status NOT NULL DEFAULT 'ACTIVE',
  allocated_by  uuid REFERENCES public.users (id) ON DELETE SET NULL,
  released_at   timestamptz,
  notes         text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),

  -- Composite FKs: the seat and the student must live in this same branch.
  CONSTRAINT fk_seat_allocations_seat
    FOREIGN KEY (seat_id, branch_id)
    REFERENCES public.seats (id, branch_id) ON DELETE RESTRICT,
  CONSTRAINT fk_seat_allocations_student
    FOREIGN KEY (student_id, branch_id)
    REFERENCES public.students (id, branch_id) ON DELETE RESTRICT,

  CONSTRAINT seat_allocations_date_order
    CHECK (end_date IS NULL OR end_date >= start_date)
);

-- One seat cannot carry two ACTIVE allocations over overlapping dates.
-- Bounds are inclusive ('[]') so a membership ending on the 30th still holds
-- the seat on the 30th — that is how staff read an end date. A NULL end_date
-- means open-ended and blocks every later allocation until released.
ALTER TABLE public.seat_allocations
  ADD CONSTRAINT excl_seat_allocations_overlap
  EXCLUDE USING gist (
    seat_id WITH =,
    daterange(start_date, end_date, '[]') WITH &&
  )
  WHERE (status = 'ACTIVE');

-- A student may not hold two active seats at once in the same branch.
ALTER TABLE public.seat_allocations
  ADD CONSTRAINT excl_student_allocations_overlap
  EXCLUDE USING gist (
    student_id WITH =,
    daterange(start_date, end_date, '[]') WITH &&
  )
  WHERE (status = 'ACTIVE');

CREATE INDEX idx_seat_allocations_branch  ON public.seat_allocations (branch_id);
CREATE INDEX idx_seat_allocations_seat    ON public.seat_allocations (seat_id);
CREATE INDEX idx_seat_allocations_student ON public.seat_allocations (student_id);
CREATE INDEX idx_seat_allocations_status  ON public.seat_allocations (status);
CREATE INDEX idx_seat_allocations_active
  ON public.seat_allocations (branch_id, seat_id)
  WHERE status = 'ACTIVE';

CREATE TRIGGER trg_seat_allocations_updated_at
  BEFORE UPDATE ON public.seat_allocations
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ========================================================================
-- 0005_batches.sql
-- ========================================================================

-- 0005 — Batches (sessions) and student enrolment.

CREATE TABLE public.batches (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id   uuid NOT NULL REFERENCES public.branches (id) ON DELETE RESTRICT,
  name        text NOT NULL,
  start_time  time NOT NULL,
  end_time    time NOT NULL,
  capacity    integer NOT NULL,
  status      batch_status NOT NULL DEFAULT 'ACTIVE',
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT batches_capacity_positive CHECK (capacity > 0),
  CONSTRAINT batches_time_order CHECK (end_time > start_time),
  CONSTRAINT uq_batches_branch_name UNIQUE (branch_id, name),
  CONSTRAINT uq_batches_id_branch UNIQUE (id, branch_id)
);

CREATE INDEX idx_batches_branch ON public.batches (branch_id);
CREATE INDEX idx_batches_status ON public.batches (status);

CREATE TRIGGER trg_batches_updated_at
  BEFORE UPDATE ON public.batches
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.batch_students (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id   uuid NOT NULL REFERENCES public.branches (id) ON DELETE RESTRICT,
  batch_id    uuid NOT NULL,
  student_id  uuid NOT NULL,
  start_date  date NOT NULL,
  end_date    date,
  status      enrollment_status NOT NULL DEFAULT 'ACTIVE',
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT fk_batch_students_batch
    FOREIGN KEY (batch_id, branch_id)
    REFERENCES public.batches (id, branch_id) ON DELETE RESTRICT,
  CONSTRAINT fk_batch_students_student
    FOREIGN KEY (student_id, branch_id)
    REFERENCES public.students (id, branch_id) ON DELETE RESTRICT,

  CONSTRAINT batch_students_date_order
    CHECK (end_date IS NULL OR end_date >= start_date)
);

-- A student holds at most one ACTIVE enrolment per batch, and at most one
-- ACTIVE batch overall (a person cannot sit in two sessions at once).
CREATE UNIQUE INDEX uq_batch_students_active
  ON public.batch_students (student_id)
  WHERE status = 'ACTIVE';

CREATE INDEX idx_batch_students_branch  ON public.batch_students (branch_id);
CREATE INDEX idx_batch_students_batch   ON public.batch_students (batch_id);
CREATE INDEX idx_batch_students_student ON public.batch_students (student_id);
CREATE INDEX idx_batch_students_active
  ON public.batch_students (batch_id)
  WHERE status = 'ACTIVE';

CREATE TRIGGER trg_batch_students_updated_at
  BEFORE UPDATE ON public.batch_students
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- --------------------------------------------------------------------------
-- Capacity guard. The API also checks capacity inside the enrolment
-- transaction (with the batch row locked) to return a clean error message;
-- this trigger is the last line of defence against any other writer.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.enforce_batch_capacity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  active_count integer;
  max_capacity integer;
BEGIN
  IF NEW.status <> 'ACTIVE' THEN
    RETURN NEW;
  END IF;

  SELECT capacity INTO max_capacity
  FROM public.batches
  WHERE id = NEW.batch_id
  FOR UPDATE;

  SELECT count(*) INTO active_count
  FROM public.batch_students
  WHERE batch_id = NEW.batch_id
    AND status = 'ACTIVE'
    AND id <> NEW.id;

  IF active_count >= max_capacity THEN
    RAISE EXCEPTION 'BATCH_CAPACITY_EXCEEDED: batch % is at capacity (%)',
      NEW.batch_id, max_capacity
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_batch_students_capacity
  BEFORE INSERT OR UPDATE OF status, batch_id ON public.batch_students
  FOR EACH ROW EXECUTE FUNCTION public.enforce_batch_capacity();


-- ========================================================================
-- 0006_admissions.sql
-- ========================================================================

-- 0006 — Admissions.

CREATE TABLE public.admissions (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  admission_number    citext NOT NULL UNIQUE,
  branch_id           uuid NOT NULL REFERENCES public.branches (id) ON DELETE RESTRICT,
  student_id          uuid NOT NULL,
  membership_plan_id  uuid NOT NULL REFERENCES public.membership_plans (id) ON DELETE RESTRICT,
  batch_id            uuid,
  seat_id             uuid,
  admission_date      date NOT NULL DEFAULT CURRENT_DATE,
  start_date          date NOT NULL,
  end_date            date NOT NULL,
  status              admission_status NOT NULL DEFAULT 'PENDING',
  notes               text,
  created_by          uuid REFERENCES public.users (id) ON DELETE SET NULL,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT fk_admissions_student
    FOREIGN KEY (student_id, branch_id)
    REFERENCES public.students (id, branch_id) ON DELETE RESTRICT,
  CONSTRAINT fk_admissions_batch
    FOREIGN KEY (batch_id, branch_id)
    REFERENCES public.batches (id, branch_id) ON DELETE RESTRICT,
  CONSTRAINT fk_admissions_seat
    FOREIGN KEY (seat_id, branch_id)
    REFERENCES public.seats (id, branch_id) ON DELETE RESTRICT,

  CONSTRAINT admissions_date_order CHECK (end_date >= start_date),
  CONSTRAINT uq_admissions_id_branch UNIQUE (id, branch_id)
);

CREATE INDEX idx_admissions_branch     ON public.admissions (branch_id);
CREATE INDEX idx_admissions_student    ON public.admissions (student_id);
CREATE INDEX idx_admissions_status     ON public.admissions (status);
CREATE INDEX idx_admissions_date       ON public.admissions (admission_date);
CREATE INDEX idx_admissions_end_date   ON public.admissions (end_date);
CREATE INDEX idx_admissions_branch_date ON public.admissions (branch_id, admission_date);

-- The student's current membership: at most one CONFIRMED admission may be
-- open at a time, which keeps "current membership" on the profile unambiguous.
CREATE UNIQUE INDEX uq_admissions_active_per_student
  ON public.admissions (student_id)
  WHERE status IN ('PENDING', 'CONFIRMED');

CREATE TRIGGER trg_admissions_updated_at
  BEFORE UPDATE ON public.admissions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ========================================================================
-- 0007_finance.sql
-- ========================================================================

-- 0007 — Invoices, invoice items, payments, fee schedules and reminders.
--
-- Financial integrity (PRD §40) is structural: `total` and `balance` are
-- GENERATED columns, so no code path — application, job or manual SQL — can
-- persist a total that disagrees with its components.

CREATE TABLE public.invoices (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_number  citext NOT NULL UNIQUE,
  branch_id       uuid NOT NULL REFERENCES public.branches (id) ON DELETE RESTRICT,
  student_id      uuid NOT NULL,
  admission_id    uuid,
  invoice_date    date NOT NULL DEFAULT CURRENT_DATE,
  due_date        date NOT NULL,
  subtotal        numeric(12, 2) NOT NULL DEFAULT 0,
  discount        numeric(12, 2) NOT NULL DEFAULT 0,
  tax             numeric(12, 2) NOT NULL DEFAULT 0,
  total           numeric(12, 2) GENERATED ALWAYS AS (subtotal - discount + tax) STORED,
  amount_paid     numeric(12, 2) NOT NULL DEFAULT 0,
  balance         numeric(12, 2) GENERATED ALWAYS AS (subtotal - discount + tax - amount_paid) STORED,
  status          invoice_status NOT NULL DEFAULT 'PENDING',
  notes           text,
  created_by      uuid REFERENCES public.users (id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT fk_invoices_student
    FOREIGN KEY (student_id, branch_id)
    REFERENCES public.students (id, branch_id) ON DELETE RESTRICT,
  CONSTRAINT fk_invoices_admission
    FOREIGN KEY (admission_id, branch_id)
    REFERENCES public.admissions (id, branch_id) ON DELETE RESTRICT,

  CONSTRAINT invoices_amounts_non_negative
    CHECK (subtotal >= 0 AND discount >= 0 AND tax >= 0 AND amount_paid >= 0),
  CONSTRAINT invoices_discount_within_subtotal
    CHECK (discount <= subtotal),
  CONSTRAINT invoices_due_after_issue
    CHECK (due_date >= invoice_date),
  CONSTRAINT uq_invoices_id_branch UNIQUE (id, branch_id)
);

-- No overpayment: amount_paid may never exceed the invoice total.
ALTER TABLE public.invoices
  ADD CONSTRAINT invoices_no_overpayment
  CHECK (amount_paid <= subtotal - discount + tax);

CREATE INDEX idx_invoices_branch     ON public.invoices (branch_id);
CREATE INDEX idx_invoices_student    ON public.invoices (student_id);
CREATE INDEX idx_invoices_status     ON public.invoices (status);
CREATE INDEX idx_invoices_due_date   ON public.invoices (due_date);
CREATE INDEX idx_invoices_date       ON public.invoices (invoice_date);
CREATE INDEX idx_invoices_branch_status ON public.invoices (branch_id, status);
CREATE INDEX idx_invoices_outstanding
  ON public.invoices (branch_id, due_date)
  WHERE status IN ('PENDING', 'PARTIALLY_PAID', 'OVERDUE');

CREATE TRIGGER trg_invoices_updated_at
  BEFORE UPDATE ON public.invoices
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.invoice_items (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id   uuid NOT NULL REFERENCES public.invoices (id) ON DELETE CASCADE,
  description  text NOT NULL,
  quantity     integer NOT NULL DEFAULT 1,
  unit_price   numeric(12, 2) NOT NULL,
  amount       numeric(12, 2) GENERATED ALWAYS AS (unit_price * quantity) STORED,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT invoice_items_quantity_positive CHECK (quantity > 0),
  CONSTRAINT invoice_items_price_non_negative CHECK (unit_price >= 0),
  CONSTRAINT invoice_items_description_not_blank CHECK (length(btrim(description)) > 0)
);

CREATE INDEX idx_invoice_items_invoice ON public.invoice_items (invoice_id);

-- --------------------------------------------------------------------------
-- Payments. Records are never hard-deleted (PRD §40.5). A correction inserts
-- a compensating row with a negative amount pointing at the original, so the
-- ledger stays append-only and auditable.
-- --------------------------------------------------------------------------
CREATE TABLE public.payments (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id              uuid NOT NULL REFERENCES public.branches (id) ON DELETE RESTRICT,
  invoice_id             uuid NOT NULL,
  student_id             uuid NOT NULL,
  amount                 numeric(12, 2) NOT NULL,
  payment_method         payment_method NOT NULL,
  transaction_reference  text,
  payment_date           date NOT NULL DEFAULT CURRENT_DATE,
  status                 payment_status NOT NULL DEFAULT 'COMPLETED',
  reverses_payment_id    uuid REFERENCES public.payments (id) ON DELETE RESTRICT,
  notes                  text,
  recorded_by            uuid REFERENCES public.users (id) ON DELETE SET NULL,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT fk_payments_invoice
    FOREIGN KEY (invoice_id, branch_id)
    REFERENCES public.invoices (id, branch_id) ON DELETE RESTRICT,
  CONSTRAINT fk_payments_student
    FOREIGN KEY (student_id, branch_id)
    REFERENCES public.students (id, branch_id) ON DELETE RESTRICT,

  -- Ordinary receipts are positive; reversals are negative and must reference
  -- the payment they undo.
  CONSTRAINT payments_signed_amount CHECK (
    (reverses_payment_id IS NULL AND amount > 0)
    OR (reverses_payment_id IS NOT NULL AND amount < 0)
  )
);

-- A payment can be reversed at most once.
CREATE UNIQUE INDEX uq_payments_single_reversal
  ON public.payments (reverses_payment_id)
  WHERE reverses_payment_id IS NOT NULL;

CREATE INDEX idx_payments_branch   ON public.payments (branch_id);
CREATE INDEX idx_payments_invoice  ON public.payments (invoice_id);
CREATE INDEX idx_payments_student  ON public.payments (student_id);
CREATE INDEX idx_payments_date     ON public.payments (payment_date);
CREATE INDEX idx_payments_branch_date ON public.payments (branch_id, payment_date);

CREATE TRIGGER trg_payments_updated_at
  BEFORE UPDATE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- --------------------------------------------------------------------------
-- Fee schedules and reminders.
-- --------------------------------------------------------------------------
CREATE TABLE public.fee_schedules (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id   uuid NOT NULL REFERENCES public.branches (id) ON DELETE RESTRICT,
  student_id  uuid NOT NULL,
  invoice_id  uuid,
  amount      numeric(12, 2) NOT NULL,
  due_date    date NOT NULL,
  status      fee_schedule_status NOT NULL DEFAULT 'UPCOMING',
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT fk_fee_schedules_student
    FOREIGN KEY (student_id, branch_id)
    REFERENCES public.students (id, branch_id) ON DELETE RESTRICT,
  CONSTRAINT fk_fee_schedules_invoice
    FOREIGN KEY (invoice_id, branch_id)
    REFERENCES public.invoices (id, branch_id) ON DELETE RESTRICT,

  CONSTRAINT fee_schedules_amount_positive CHECK (amount > 0)
);

-- One schedule row per invoice keeps the reminder job idempotent.
CREATE UNIQUE INDEX uq_fee_schedules_invoice
  ON public.fee_schedules (invoice_id)
  WHERE invoice_id IS NOT NULL;

CREATE INDEX idx_fee_schedules_branch   ON public.fee_schedules (branch_id);
CREATE INDEX idx_fee_schedules_student  ON public.fee_schedules (student_id);
CREATE INDEX idx_fee_schedules_due_date ON public.fee_schedules (due_date);
CREATE INDEX idx_fee_schedules_status   ON public.fee_schedules (status);
CREATE INDEX idx_fee_schedules_pending
  ON public.fee_schedules (due_date)
  WHERE status IN ('UPCOMING', 'DUE', 'OVERDUE');

CREATE TRIGGER trg_fee_schedules_updated_at
  BEFORE UPDATE ON public.fee_schedules
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.fee_reminders (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id        uuid NOT NULL REFERENCES public.branches (id) ON DELETE RESTRICT,
  student_id       uuid NOT NULL,
  fee_schedule_id  uuid NOT NULL REFERENCES public.fee_schedules (id) ON DELETE CASCADE,
  reminder_type    reminder_type NOT NULL,
  reminder_date    date NOT NULL,
  status           reminder_status NOT NULL DEFAULT 'PENDING',
  provider         text,
  error_message    text,
  sent_at          timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT fk_fee_reminders_student
    FOREIGN KEY (student_id, branch_id)
    REFERENCES public.students (id, branch_id) ON DELETE RESTRICT
);

-- Idempotency key for the reminder job: re-running it on the same day can
-- never produce a second reminder of the same kind for the same fee.
CREATE UNIQUE INDEX uq_fee_reminders_idempotency
  ON public.fee_reminders (fee_schedule_id, reminder_type, reminder_date);

CREATE INDEX idx_fee_reminders_branch ON public.fee_reminders (branch_id);
CREATE INDEX idx_fee_reminders_status ON public.fee_reminders (status);

CREATE TRIGGER trg_fee_reminders_updated_at
  BEFORE UPDATE ON public.fee_reminders
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ========================================================================
-- 0008_attendance_biometric.sql
-- ========================================================================

-- 0008 — Attendance, biometric devices and biometric user mapping.

CREATE TABLE public.biometric_devices (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id          uuid NOT NULL REFERENCES public.branches (id) ON DELETE RESTRICT,
  name               text NOT NULL,
  device_identifier  citext NOT NULL UNIQUE,
  ip_address         inet,
  api_endpoint       text,
  status             device_status NOT NULL DEFAULT 'ACTIVE',
  last_sync_at       timestamptz,
  last_error         text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_biometric_devices_id_branch UNIQUE (id, branch_id)
);

CREATE INDEX idx_biometric_devices_branch ON public.biometric_devices (branch_id);

CREATE TRIGGER trg_biometric_devices_updated_at
  BEFORE UPDATE ON public.biometric_devices
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Maps a device-local user id to a student. The composite FKs guarantee the
-- device, the student and the mapping all belong to the same branch (PRD §26).
CREATE TABLE public.biometric_mappings (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id          uuid NOT NULL REFERENCES public.branches (id) ON DELETE RESTRICT,
  device_id          uuid NOT NULL,
  biometric_user_id  text NOT NULL,
  student_id         uuid NOT NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT fk_biometric_mappings_device
    FOREIGN KEY (device_id, branch_id)
    REFERENCES public.biometric_devices (id, branch_id) ON DELETE CASCADE,
  CONSTRAINT fk_biometric_mappings_student
    FOREIGN KEY (student_id, branch_id)
    REFERENCES public.students (id, branch_id) ON DELETE RESTRICT,

  CONSTRAINT uq_biometric_mappings_device_user UNIQUE (device_id, biometric_user_id),
  CONSTRAINT uq_biometric_mappings_device_student UNIQUE (device_id, student_id)
);

CREATE INDEX idx_biometric_mappings_branch  ON public.biometric_mappings (branch_id);
CREATE INDEX idx_biometric_mappings_student ON public.biometric_mappings (student_id);

CREATE TRIGGER trg_biometric_mappings_updated_at
  BEFORE UPDATE ON public.biometric_mappings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- --------------------------------------------------------------------------
-- Attendance
-- --------------------------------------------------------------------------
CREATE TABLE public.attendance (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id            uuid NOT NULL REFERENCES public.branches (id) ON DELETE RESTRICT,
  student_id           uuid NOT NULL,
  batch_id             uuid,
  attendance_date      date NOT NULL,
  check_in_time        timestamptz,
  check_out_time       timestamptz,
  status               attendance_status NOT NULL DEFAULT 'PRESENT',
  source               attendance_source NOT NULL DEFAULT 'MANUAL',
  device_id            uuid,
  biometric_record_id  text,
  notes                text,
  recorded_by          uuid REFERENCES public.users (id) ON DELETE SET NULL,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT fk_attendance_student
    FOREIGN KEY (student_id, branch_id)
    REFERENCES public.students (id, branch_id) ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_batch
    FOREIGN KEY (batch_id, branch_id)
    REFERENCES public.batches (id, branch_id) ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_device
    FOREIGN KEY (device_id, branch_id)
    REFERENCES public.biometric_devices (id, branch_id) ON DELETE SET NULL,

  CONSTRAINT attendance_time_order
    CHECK (check_out_time IS NULL OR check_in_time IS NULL OR check_out_time >= check_in_time),
  CONSTRAINT attendance_biometric_has_device
    CHECK (source <> 'BIOMETRIC' OR device_id IS NOT NULL)
);

-- Deduplication (PRD §27), two independent layers:
--   1. one attendance row per student per day, whatever the source;
--   2. a device's record id can only ever be ingested once.
CREATE UNIQUE INDEX uq_attendance_student_day
  ON public.attendance (student_id, attendance_date);

CREATE UNIQUE INDEX uq_attendance_biometric_record
  ON public.attendance (device_id, biometric_record_id)
  WHERE biometric_record_id IS NOT NULL;

CREATE INDEX idx_attendance_branch   ON public.attendance (branch_id);
CREATE INDEX idx_attendance_student  ON public.attendance (student_id);
CREATE INDEX idx_attendance_date     ON public.attendance (attendance_date);
CREATE INDEX idx_attendance_batch    ON public.attendance (batch_id);
CREATE INDEX idx_attendance_branch_date ON public.attendance (branch_id, attendance_date);

CREATE TRIGGER trg_attendance_updated_at
  BEFORE UPDATE ON public.attendance
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Raw device events, kept before mapping so an unmapped punch is never lost
-- and a re-sync of the same window is a no-op.
CREATE TABLE public.biometric_events (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id            uuid NOT NULL REFERENCES public.branches (id) ON DELETE RESTRICT,
  device_id            uuid NOT NULL,
  biometric_record_id  text NOT NULL,
  biometric_user_id    text NOT NULL,
  event_time           timestamptz NOT NULL,
  direction            text,
  processed            boolean NOT NULL DEFAULT false,
  student_id           uuid,
  attendance_id        uuid REFERENCES public.attendance (id) ON DELETE SET NULL,
  error_message        text,
  raw_payload          jsonb,
  created_at           timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT fk_biometric_events_device
    FOREIGN KEY (device_id, branch_id)
    REFERENCES public.biometric_devices (id, branch_id) ON DELETE CASCADE,
  CONSTRAINT uq_biometric_events_record UNIQUE (device_id, biometric_record_id),
  CONSTRAINT biometric_events_direction
    CHECK (direction IS NULL OR direction IN ('IN', 'OUT'))
);

CREATE INDEX idx_biometric_events_unprocessed
  ON public.biometric_events (device_id, event_time)
  WHERE NOT processed;


-- ========================================================================
-- 0009_audit_and_sequences.sql
-- ========================================================================

-- 0009 — Audit log and per-branch document number sequences.

CREATE TABLE public.audit_logs (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id    uuid REFERENCES public.branches (id) ON DELETE SET NULL,
  user_id      uuid REFERENCES public.users (id) ON DELETE SET NULL,
  action       text NOT NULL,
  entity_type  text NOT NULL,
  entity_id    uuid,
  metadata     jsonb,
  ip_address   inet,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_logs_branch  ON public.audit_logs (branch_id);
CREATE INDEX idx_audit_logs_user    ON public.audit_logs (user_id);
CREATE INDEX idx_audit_logs_entity  ON public.audit_logs (entity_type, entity_id);
CREATE INDEX idx_audit_logs_created ON public.audit_logs (created_at DESC);

COMMENT ON COLUMN public.audit_logs.metadata IS
  'Business context only. Never store passwords, tokens or API keys here.';

-- --------------------------------------------------------------------------
-- Human-readable document numbers, unique per branch and year:
--   ADM-MLB-2026-000123
--   INV-MLB-2026-000123
-- The counter row is locked for the rest of the calling transaction, so
-- numbers never collide under concurrency.
-- --------------------------------------------------------------------------
CREATE TABLE public.document_sequences (
  branch_id    uuid NOT NULL REFERENCES public.branches (id) ON DELETE CASCADE,
  doc_type     text NOT NULL,
  year         integer NOT NULL,
  last_number  integer NOT NULL DEFAULT 0,
  PRIMARY KEY (branch_id, doc_type, year),
  CONSTRAINT document_sequences_type
    CHECK (doc_type IN ('ADMISSION', 'INVOICE', 'STUDENT'))
);

CREATE OR REPLACE FUNCTION public.next_document_number(
  p_branch_id uuid,
  p_doc_type  text,
  p_prefix    text
)
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
  v_year        integer := EXTRACT(YEAR FROM CURRENT_DATE)::integer;
  v_next        integer;
  v_branch_code text;
BEGIN
  SELECT branch_code INTO v_branch_code
  FROM public.branches
  WHERE id = p_branch_id;

  IF v_branch_code IS NULL THEN
    RAISE EXCEPTION 'Unknown branch %', p_branch_id USING ERRCODE = 'foreign_key_violation';
  END IF;

  INSERT INTO public.document_sequences (branch_id, doc_type, year, last_number)
  VALUES (p_branch_id, p_doc_type, v_year, 1)
  ON CONFLICT (branch_id, doc_type, year)
  DO UPDATE SET last_number = public.document_sequences.last_number + 1
  RETURNING last_number INTO v_next;

  RETURN format('%s-%s-%s-%s',
                p_prefix,
                upper(v_branch_code::text),
                v_year,
                lpad(v_next::text, 6, '0'));
END;
$$;

COMMENT ON FUNCTION public.next_document_number(uuid, text, text) IS
  'Call inside the same transaction as the row being numbered so a rollback releases the number.';


-- ========================================================================
-- 0010_row_level_security.sql
-- ========================================================================

-- 0010 — Row Level Security.
--
-- Second line of defence (PRD §6). The Node API connects as the database
-- owner and is therefore NOT subject to these policies — it enforces branch
-- access itself in code. RLS exists for the browser session, which holds a
-- Supabase `authenticated` JWT and subscribes to Realtime channels directly.
--
-- Policy shape for the browser:
--   * SELECT  — only rows in a branch the user is assigned to.
--   * INSERT/UPDATE/DELETE — never. All writes go through the API so business
--     rules, transactions and audit logging cannot be bypassed.

ALTER TABLE public.branches           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_branches      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership_plans   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seats              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seat_allocations   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.batches            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.batch_students     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admissions         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_items      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fee_schedules      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fee_reminders      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.biometric_devices  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.biometric_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.biometric_events   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_sequences ENABLE ROW LEVEL SECURITY;

-- document_sequences and biometric_events carry no browser-facing use case:
-- RLS enabled with zero policies means deny-all for non-owner roles.

-- --------------------------------------------------------------------------
-- Identity
-- --------------------------------------------------------------------------
CREATE POLICY branches_select ON public.branches
  FOR SELECT TO authenticated
  USING (public.has_branch_access(id));

CREATE POLICY roles_select ON public.roles
  FOR SELECT TO authenticated
  USING (true);

CREATE POLICY users_select_self ON public.users
  FOR SELECT TO authenticated
  USING (id = auth.uid() OR public.is_super_admin());

CREATE POLICY user_branches_select_self ON public.user_branches
  FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.is_super_admin());

CREATE POLICY membership_plans_select ON public.membership_plans
  FOR SELECT TO authenticated
  USING (true);

-- --------------------------------------------------------------------------
-- Branch-scoped operational data
-- --------------------------------------------------------------------------
CREATE POLICY students_select ON public.students
  FOR SELECT TO authenticated USING (public.has_branch_access(branch_id));

CREATE POLICY seats_select ON public.seats
  FOR SELECT TO authenticated USING (public.has_branch_access(branch_id));

CREATE POLICY seat_allocations_select ON public.seat_allocations
  FOR SELECT TO authenticated USING (public.has_branch_access(branch_id));

CREATE POLICY batches_select ON public.batches
  FOR SELECT TO authenticated USING (public.has_branch_access(branch_id));

CREATE POLICY batch_students_select ON public.batch_students
  FOR SELECT TO authenticated USING (public.has_branch_access(branch_id));

CREATE POLICY admissions_select ON public.admissions
  FOR SELECT TO authenticated USING (public.has_branch_access(branch_id));

CREATE POLICY invoices_select ON public.invoices
  FOR SELECT TO authenticated USING (public.has_branch_access(branch_id));

CREATE POLICY payments_select ON public.payments
  FOR SELECT TO authenticated USING (public.has_branch_access(branch_id));

CREATE POLICY fee_schedules_select ON public.fee_schedules
  FOR SELECT TO authenticated USING (public.has_branch_access(branch_id));

CREATE POLICY fee_reminders_select ON public.fee_reminders
  FOR SELECT TO authenticated USING (public.has_branch_access(branch_id));

CREATE POLICY attendance_select ON public.attendance
  FOR SELECT TO authenticated USING (public.has_branch_access(branch_id));

CREATE POLICY biometric_devices_select ON public.biometric_devices
  FOR SELECT TO authenticated USING (public.has_branch_access(branch_id));

CREATE POLICY biometric_mappings_select ON public.biometric_mappings
  FOR SELECT TO authenticated USING (public.has_branch_access(branch_id));

CREATE POLICY audit_logs_select ON public.audit_logs
  FOR SELECT TO authenticated
  USING (branch_id IS NOT NULL AND public.has_branch_access(branch_id));

-- invoice_items inherit their parent invoice's branch.
CREATE POLICY invoice_items_select ON public.invoice_items
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.invoices i
    WHERE i.id = invoice_items.invoice_id
      AND public.has_branch_access(i.branch_id)
  ));

-- --------------------------------------------------------------------------
-- Realtime publication. Only the tables whose changes the dashboards react to
-- (PRD §41); every subscriber is still filtered by the SELECT policies above.
-- --------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE
      public.seats,
      public.seat_allocations,
      public.attendance,
      public.invoices,
      public.payments,
      public.fee_schedules;
  END IF;
END;
$$;


-- ========================================================================
-- Migration bookkeeping
-- ========================================================================

CREATE TABLE IF NOT EXISTS public.schema_migrations (
  name        text PRIMARY KEY,
  checksum    text NOT NULL,
  applied_at  timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.schema_migrations (name, checksum) VALUES
  ('0001_extensions_and_enums.sql', 'df133cb9c8238ad6'),
  ('0002_core_identity.sql', 'e942be70fa65236b'),
  ('0003_students_memberships.sql', '3c978bb9768264ce'),
  ('0004_seats_allocations.sql', '9f58eceb0c97eeef'),
  ('0005_batches.sql', '04630b5918db8863'),
  ('0006_admissions.sql', '790ad68749545bc0'),
  ('0007_finance.sql', '7a50b264a1229982'),
  ('0008_attendance_biometric.sql', 'e60102eda7f1cb48'),
  ('0009_audit_and_sequences.sql', '7ddd7c952bb097c0'),
  ('0010_row_level_security.sql', '4a5b264ac6abfa05')
ON CONFLICT (name) DO NOTHING;

COMMIT;

-- Verify:  SELECT name, applied_at FROM public.schema_migrations ORDER BY name;
